### ISSUE TITLE
What is the code for LLM-MCTS result corresponding to?

### ISSUE THREAD

**Issue by weizhenFrank** [1989Ryan/llm-mcts#1]
Hi,

Thanks for sharing your code for your paper "Large Language Models as Commonsense Knowledge for Large-Scale Task Planning". L-model and L-policy framework is a very interesting and quite effective idea! 

I'm trying to run your code, and I have two questions,

1. The original code can't find ```data/object_info.json```, so I copy ```vh/data_gene/dataset/object_info.json```
 to ```./data/object_info.json```, but I also find another ```object_info.json``` in ```vh/data_gene/gen_data/data/object_info.json```, whic one should I use?

2. I used ```vh/data_gene/dataset/object_info.json```, and copy "objects_switchonoff" from ```vh/data_gene/gen_data/data/object_info.json``` to ```./data/object_info.json``` as ```vh/data_gene/dataset/object_info.json ```don't have such part. So I run the code  for LLM-MCTS. But finally I got ```succ rate:  0.3125```. Is this correct? 

Can you explain the code generate which result?
```python mcts/virtualhome/mcts_agent.py \
    --exploration_constant 24 \
    --max_episode_len 50 \
    --max_depth 20 \
    --round 0 \
    --simulation_per_act 2 \
    --simulation_num 100 \
    --discount_factor 0.95  \
    --uct_type PUCT \
    --mode simple \
    --seen_item \
    --seen_apartment\
    --seen_comp
```
Is this Seen Home and NovelComp.(3)in your Table 1?

<img width="757" alt="image" src="https://github.com/1989Ryan/llm-mcts/assets/37463904/2c4c0a26-4a81-49bb-971f-a546556de2d4">

**Comment by 1989Ryan** [comment]
Thank you for your feedback. The file has been uploaded, and the bug has been fixed. Please check out the latest code.

**Comment by 1989Ryan** [comment]
Thank you for your feedback. The file has been uploaded, and the bug has been fixed. Please check out the latest code.
