### ISSUE TITLE
Two questions regarding data generation

### ISSUE THREAD

**Issue by AlexWanghaoming** [1989Ryan/llm-mcts#4]
Hi, I have two questions about date generation in virtualhome:
1. I have generated the goal of a domain using `vh/data_gene/gen_data/vh_init.py` and the result in pickle is comprised of task_id, task_name, env_id, init_graph, task_goal, level and init_rooms. How can I know the task instruction? 
2. When I generated expert data using `python vh/data_gene/testing_agents/gene_data.py --mode simple --dataset_path ./vh/dataset/env_task_set_50_simple.pik `, an error  `Time out for action:  {0: None}`  occurs at [this line](https://github.com/1989Ryan/watch_and_help/blob/88946995b4d8a23b1ddc20990ed40b5300155f2f/testing_agents/gene_data.py#L119). This erros appeared randomly. Could you please help to solve it? 

Thank you

**Comment by 1989Ryan** [comment]
Hi, the instructions will be generated in the later steps. `vh/data_gene/gen_data/vh_init.py` only generates the environment set-up. 

Unfortunately, I cannot replicate your errors in your 2nd point. It would be great if you could provide more detailed information regarding your errors. Before that, I would suggest you take a look at this guidance: https://github.com/wanbiao1993usa/llm-mcts.

**Comment by AlexWanghaoming** [comment]
Hi,

Thanks for your reply. I just follow the guidance you provide. But when I run  `python vh/data_gene/testing_agents/gene_data.py --mode simple --dataset_path ./vh/dataset/env_task_set_50_simple.pik`, an error  `ValueError: too many values to unpack (expected 4)` occurs at [this line](https://github.com/1989Ryan/watch_and_help/blob/88946995b4d8a23b1ddc20990ed40b5300155f2f/algos/arena_mp2.py#L380) 
. I modified the line to `(obs, reward, done, env_info, _ ), agent_actions, agent_info = self.step(true_graph=is_train)
` and the error seems being solved. Could you please figure out which step will generate task instructions?

Best

**Comment by 1989Ryan** [comment]
Hi, the error is caused by the wrong submodule branch. You can go to the submodule `vh/data_gene` and switch to the `main` branch. The repo is updated accordingly. Thank you!
